# Generated by Django 6.0.6 on 2026-10-07 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehicleasset_operatorprofile_vehicleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='deployment_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deployment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Maintenance'), ('DEPLOYED', 'Deployed'), ('PENDING_DISPOSAL', 'Pending Disposal'), ('ARCHIVED', 'Archived')], default='OPERATIONAL', max_length=50),
        ),
    ]
