# Generated by Django 6.0.6 on 2026-10-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehicleasset_operatorprofile_vehicleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('contact_number', models.CharField(max_length=30)),
                ('purpose', models.CharField(choices=[('EMERGENCY_RESPONSE', 'Emergency response'), ('MEDICAL_TRANSPORT', 'Medical transport'), ('RESCUE_OPERATION', 'Rescue operation'), ('OFFICIAL_BUSINESS', 'Official business'), ('LOGISTICS_SUPPORT', 'Logistics support'), ('OTHER', 'Other')], max_length=30)),
                ('vehicle_category', models.CharField(choices=[('LAND', 'Land vehicle'), ('SEA', 'Seacraft')], max_length=4)),
                ('requested_for', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('staff_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'vehicle request',
                'verbose_name_plural': 'vehicle requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
