# Generated by Django 6.0.6 on 2026-10-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_vehicle_deployment_location_vehicle_deployment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='deployment_purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
