# Generated by Django 6.0.6 on 2026-10-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_vehiclerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequest',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_requests', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='tracking_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='tracking_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
    ]
