# Generated by Django 6.0.6 on 2026-10-06 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_vehiclerequest_assigned_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequest',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_requests', to='fleet.vehicle'),
        ),
    ]
