# Generated by Django 6.0.6 on 2026-10-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_vehiclerequest_assigned_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='deployment_destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deployment_purpose',
            field=models.CharField(blank=True, choices=[('EMERGENCY_RESPONSE', 'Emergency response'), ('MEDICAL_TRANSPORT', 'Medical transport'), ('RESCUE_OPERATION', 'Rescue operation'), ('OFFICIAL_BUSINESS', 'Official business'), ('LOGISTICS_SUPPORT', 'Logistics support'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
