# Generated by Django 6.0.6 on 2026-10-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_vehicle_maintenance_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='scheduled_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scheduled_maintenance_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scheduled_maintenance_type',
            field=models.CharField(blank=True, choices=[('TIRES', 'Tire replacement'), ('OIL', 'Oil replacement'), ('OTHER', 'Other maintenance')], max_length=20),
        ),
    ]
