# Generated by Django 6.0.6 on 2026-10-09 02:44

from django.db import migrations, models


def classify_existing_operators(apps, schema_editor):
    Driver = apps.get_model('fleet', 'Driver')
    Driver.objects.filter(license_number__istartswith='MAR-').update(
        license_authority='MARINA',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_vehicle_scheduled_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_authority',
            field=models.CharField(choices=[('LTO', 'LTO - Land Transportation Office'), ('MARINA', 'MARINA - Maritime Industry Authority')], default='LTO', max_length=10),
        ),
        migrations.RunPython(classify_existing_operators, migrations.RunPython.noop),
    ]
