# Generated by Django 6.0.6 on 2026-10-06 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_vehicle_deployment_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('DAMAGED', 'Damaged'), ('DESTROYED', 'Destroyed')], max_length=10)),
                ('description', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('OPEN', 'Needs review'), ('REVIEWED', 'Reviewed')], default='OPEN', max_length=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_condition_reports', to='fleet.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_reports', to='fleet.vehicle')),
                ('vehicle_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_condition_reports', to='fleet.vehiclerequest')),
            ],
            options={
                'verbose_name': 'unit condition report',
                'verbose_name_plural': 'unit condition reports',
                'ordering': ['-reported_at'],
            },
        ),
    ]
