# Generated by Django 6.0.6 on 2026-10-09 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_driver_license_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('COLLISION', 'Collision'), ('BREAKDOWN', 'Breakdown during operation'), ('DAMAGE', 'Asset or equipment damage'), ('SAFETY', 'Safety incident'), ('OTHER', 'Other incident')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('damage_details', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_incident_reports', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to='fleet.vehicle')),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
            },
        ),
    ]
