# Generated by Django 6.0.6 on 2026-10-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_fleetincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetincident',
            name='last_assigned_driver',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
