# Generated by Django 6.0.6 on 2026-10-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='maintenance_problem',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
