# Generated by Django 6.0.6 on 2026-10-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_fleetincident_last_assigned_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetincident',
            name='actions_taken',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='fleetincident',
            name='follow_up_recommendations',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='fleetincident',
            name='injury_details',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='fleetincident',
            name='injury_status',
            field=models.CharField(choices=[('NO', 'No injuries reported'), ('YES', 'Injuries reported'), ('UNKNOWN', 'Unknown / not confirmed')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='fleetincident',
            name='witnesses',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
