# Generated by Django 6.0.6 on 2026-10-10 02:24

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def backfill_maintenance_started_at(apps, schema_editor):
    Vehicle = apps.get_model('fleet', 'Vehicle')
    vehicles = Vehicle.objects.filter(
        status__in=['MAINTENANCE', 'PENDING_DISPOSAL'],
        maintenance_started_at__isnull=True,
    ).order_by('pk').values_list('pk', flat=True)
    base_time = timezone.now()
    for index, vehicle_id in enumerate(vehicles.iterator()):
        Vehicle.objects.filter(pk=vehicle_id).update(
            maintenance_started_at=base_time + timedelta(microseconds=index)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_vehicle_color_vehicle_make_vehicle_model_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='maintenance_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_maintenance_started_at,
            migrations.RunPython.noop,
        ),
    ]
