# Generated by Django 6.0.6 on 2026-10-10 02:34

from django.db import migrations, models


def backfill_maintenance_last_assigned_driver(apps, schema_editor):
    Vehicle = apps.get_model('fleet', 'Vehicle')
    Driver = apps.get_model('fleet', 'Driver')
    vehicles = Vehicle.objects.filter(
        status__in=['MAINTENANCE', 'PENDING_DISPOSAL'],
        assigned_driver__isnull=False,
    ).values_list('pk', 'assigned_driver_id')
    driver_names = dict(Driver.objects.filter(
        pk__in=[driver_id for _, driver_id in vehicles]
    ).values_list('pk', 'name'))
    for vehicle_id, driver_id in vehicles:
        Vehicle.objects.filter(pk=vehicle_id).update(
            maintenance_last_assigned_driver=driver_names.get(driver_id, '')
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_vehicle_maintenance_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='maintenance_last_assigned_driver',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(
            backfill_maintenance_last_assigned_driver,
            migrations.RunPython.noop,
        ),
    ]
